### ISSUE TITLE
Error recieved with Angular-CLI 1.5.0 build converting t Angular 5.0

### ISSUE THREAD

**Issue by ghaddon** [spirosikmd/angular2-focus#58]
I get the following error when running NG Build on Angular-CLI 1.5.0. I was converting over to Angular 5.0. When I removed module everything worked.

ERROR in TypeError: staticSymbol.assertNoMembers is not a function
    at AotSummaryResolver.resolveSummary (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:31928:22)
    at CompileMetadataResolver._loadSummary (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:14709:66)
    at CompileMetadataResolver.isDirective (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:15003:23)
    at CompileMetadataResolver._getTypeDescriptor (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:15269:18)
    at C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:15131:78
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:15114:49)
    at visitLazyRoute (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:29937:104)
    at AotCompiler.listLazyRoutes (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler\bundles\compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler-cli\src\transformers\program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (C:\Users\Gary\WebstormProjects\ConstituentManager2\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:542:50)
    at <anonymous>

**Comment by spirosikmd** [comment]
Hi @ghaddon! Thank you for submitting this issue. I guess I need to update module to work with latest angular!

**Comment by ghaddon** [comment]
Thanks for looking into this issue.


   On Monday, November 6, 2017, 1:07:04 AM MST, Spyros Ioakeimidis <notifications@github.com> wrote: 
 
 
Hi @ghaddon! Thank you for submitting this issue. I guess I need to update module to work with latest angular!

**Comment by spirosikmd** [comment]
Hi @ghaddon! Please have a look at the conversation in spirosikmd/angular-elastic-input#40. This seems to be a cli configuration issue. When I try the docs example with latest angular everything works for me. Maybe you can provide a way to reproduce your issue?

**Comment by raleesound** [comment]
Your problem is that you have @angular/core: "^4.0.0" in your dependencies. This makes NPM/Yarn install @angular/core under ng2-focus, and Angular really doesn't like it when you have two different versions running. You should really move all of your @angular runtime dependencies to peerDependencies (and, obviously upgrade them to ^5.0.0 AFTER you have tested your library against Angular 5) -- then it will just warn users on install if they don't have the specified version.

**Comment by spirosikmd** [comment]
Hi @raleesound! I tested the library with Angular 5 and it works. Please clone the repo and check the [docs](https://github.com/spirosikmd/angular2-focus/tree/master/docs) directory that contains an example. Also the versions in `package.json` point to "^5.0.1". Moving `@angular/core` from dependencies to peerDependencies does make sense. Thank you for the recommendation.

**Comment by ghaddon** [comment]
Hello Spirosokmd.
I had some time and just tried to rebuild my application with Angular2-Focus and got the following error. I'm current on all Angular 5 modules. I include a listing from my angular-cli.

I will say the message is different than first reported. It looks like it is looking for the TypeScript definitions module.

I agree I believe the error is an angular-cli compilation error. I just don't know how or where to start looking for an error like I'm getting.

If I can try something just let me know. I'll be happy to help try something to help debug the problem.

**** Error Message ***

ERROR in ./node_modules/angular2-focus/src/focus.module.ts
Module build failed: Error: C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\angular2-focus\src\focus.module.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular2-focus/index.js 6:9-38

Below is the version of Angular 5 modules I have in my package.json.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

**Comment by spirosikmd** [comment]
Hi @ghaddon! According to angular/angular#20091, maybe adding the following to your `tsconfig.json` would solve this issue?

```diff
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -15,5 +15,9 @@
       "es2017",
       "dom"
     ]
-  }
+  },
+  "include": [
+    "src/**/*",
+    "node_modules/angular2-focus/index.ts"
+  ]
 }
```

**Comment by ghaddon** [comment]
Hi, @spirosikmd  I tried the last suggestion and got the following error on NG BUILD.

WARNING in ./node_modules/angular2-focus/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/angular2-focus/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-focus/src/focus.module.ts
 @ ./node_modules/angular2-focus/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular2-focus/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Users\Gary\WebstormProjects\GaryTest50\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/angular2-focus/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-focus/src/focus.module.ts
 @ ./node_modules/angular2-focus/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by dizhar** [comment]
Hi, I am getting the following error after I upgraded from Angular4 to Angular5.

ERROR in ./node_modules/angular2-focus/src/focus.module.ts
Module build failed: Error: C:\loltlv\node_modules\angular2-focus\src\focus.module.ts is not part of the compilation output. Please check the other error m
essages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\loltlv\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (C:\loltlv\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/angular2-focus/index.js 6:9-38
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./node_modules/ng2-file-drop/index.ts
Module build failed: Error: C:\loltlv\node_modules\ng2-file-drop\index.ts is not part of the compilation output. Please check the other error messages for
details.
    at AngularCompilerPlugin.getCompiledFile (C:\loltlv\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:624:23)
    at plugin.done.then (C:\loltlv\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/upload/upload.module.ts 15:0-50
 @ ./src/app/navbar/navbar.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
